openapi: 3.0.1
info:
  title: Movement API
  version: 1.0.0

servers:
  - url: http://localhost:8082

paths:
  /movements:
    get:
      summary: Listar todos los movimientos
      operationId: getAllMovements
      responses:
        '200':
          description: Lista de movimientos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'

    post:
      summary: Crear un movimiento
      operationId: createMovement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRequest'
      responses:
        '201':
          description: Movimiento creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'

  /movements/{id}:
    get:
      summary: Obtener movimiento por ID
      operationId: getMovementById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movimiento encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
    put:
      summary: Actualizar movimiento
      operationId: updateMovement
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRequest'
      responses:
        '200':
          description: Movimiento actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
    delete:
      summary: Eliminar movimiento
      operationId: deleteMovement
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Movimiento eliminado

  /movements/customer/{customerId}:
    get:
      summary: Obtener movimientos por customerId
      operationId: getMovementsByCustomerId
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de movimientos del cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'

  /movements/last10/{productId}:
    get:
      summary: Obtener los últimos 10 movimientos por producto
      operationId: getLast10Movements
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de últimos 10 movimientos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'

  /movements/report/{productId}:
    get:
      summary: Generar reporte de movimientos por producto en rango de fechas
      operationId: getMovementReport
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            example: "2025-08-31T00:00:00"
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            example: "2025-09-02T23:59:59"
      responses:
        "200":
          description: Reporte generado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementReportResponse'

components:
  schemas:
    MovementRequest:
      type: object
      required:
        - productId
        - customerId
        - type
      properties:
        productId:
          type: string
        customerId:
          type: string
        type:
          type: string
          enum: [DEPOSITO, RETIRO, TRANSFERENCIA]
        amount:
          type: number
        date:
          type: string
        description:
          type: string

    MovementResponse:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        customerId:
          type: string
        type:
          type: string
          enum: [ DEPOSITO, RETIRO, TRANSFERENCIA ]
        amount:
          type: number
        date:
          type: string
          format: date-time
        description:
          type: string

    MovementReportResponse:
      type: object
      properties:
        productId:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        movements:
          type: array
          items:
            $ref: "#/components/schemas/MovementResponse"
